CREATE TABLE IF NOT EXISTS STUDENT
(
    SNO   VARCHAR(50) NOT NULL,
    SNAME VARCHAR(50) NOT NULL,
    SSEX  CHAR(2)     NOT NULL
);
INSERT INTO STUDENT
VALUES ('001', 'KangKang', 'M');
INSERT INTO STUDENT
VALUES ('002', 'Mike', 'M');
INSERT INTO STUDENT
VALUES ('003', 'Jane', 'F');